config/routes.rb
GeekArc::Application.routes.draw do
  root :to => 'welcome#index'
  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  resources :sessions

  resources :blog, :controller => "posts"
end

app/models/port.rb
class Port < ActiveRecord::Base
  attr_accessible :content, :date, :title

  has_many :tags
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :date, :title

  has_many :tags
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name, :uniqueness => true

  has_and_belongs_to_many :posts
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  attr_accessible :username, :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
  def not_authenticated
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  before_filter :require_login, :except => [:index, :show]


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :require_login, :except => [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.unscoped.all(:select => [:id, :date, :title, :content], :order => "updated_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to blog_path(@post), notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to blog_path(@post), notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to blog_index_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = login(params[:username], params[:password])
    if user
      redirect_back_or_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Incorrect username or password"
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_url, :notice => "Logged Out!"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	#limits the number of posts to 10 blogs posts showing
    @posts = Post.unscoped.all(:select => [:id, :date, :title, :content], :order => "updated_at DESC").first(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      :no_intra_emphasis => true,
      :fenced_code_blocks => true,
      :autolink => true
    }
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML.new(:filter_html => true, :hard_wrap => true), options)
    syntax_highlighter(markdown.render(text)).html_safe
  end

  def syntax_highlighter(html)
    doc = Nokogiri::HTML(html)
    doc.search("//pre[@lang]").each do |pre|
      pre.replace Albino.colorize(pre.text.rstrip, pre[:lang])
    end
    doc.to_s
  end
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title> Geek Architect </title>

	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>
  <div id='main-container'>

    <div id='neat-display'>
      <h1>
        <span>GEEK</span>
        <span>Architect</span>
      </h1>
    </div><!-- end neat-display -->

    <div id='nav-bar'>
      <ul class='nav'>
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Blog', blog_index_path %></li>
        <li><a href="#">Portfolio</a></li>
      </ul>
    </div><!-- end nav bar -->

    <div id='content'>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
        <% end %>
        <%= yield %>
    </div>

  </div><!-- end main -->
  </body>
</html>

app/views/posts/_form.html.erb
<% if @post.new_record? %>

  <%= form_for(@post, :url => blog_index_path(@post)) do |f| %>
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :date %><br />
      <%= f.date_select :date %>
    </div>
    <div class="field">
      <%= f.label :content %><br />
      <%= f.text_area :content %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

<% else %>

  <%= form_for(@post, :url => blog_path(@post)) do |f| %>
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :date %><br />
      <%= f.date_select :date %>
    </div>
    <div class="field">
      <%= f.label :content %><br />
      <%= f.text_area :content %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', blog_path(@post) %> |
<%= link_to 'Back', blog_index_path %>

app/views/posts/index.html.erb
<div id='wel-con' class='welcome'>
  <h1 class='words'>Blog Posts!</h1>

  <% if logged_in? %>
    <%= link_to 'New Post', new_blog_path %>
  <% end %>
</div><!-- end wel-con -->

<div id='side-feed' class='welcome'>
  <h1 class='words'>titles</h1>
  <% @posts.each do |post| %>
    <%= link_to post.title, blog_path(post) %><br>
    <%= post.date %><br><br>
  <% end %>
</div><!-- end side -->

<% @posts.each do |post| %>
<div id='blog'> 
  <div class="date-wrapper-container">
    <div class="wrapper-container">
      <%= post.date %>
    </div><!-- wrapper-container -->
  </div><!-- date-wrapper-container -->

  <h3><%= link_to post.title, blog_path(post) %></h3>

  <%= post.content %><br>

    <% if logged_in? %>
      <%= link_to 'Edit', edit_blog_path(post) %>
      <%= link_to 'Destroy', blog_path(post), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
</div><!-- end blog -->
<% end %>
    
<div id='footer'>
  <ul>
    <a href='http://www.facebook.com'><li class='facebook'>f</li></a>
    <a href='http://www.twitter.com'><li class='twitter'>t</li></a>
    <li class='me'>Created by Chris Wenner</li>
    <a href='http://www.seedcoworking.com'><li class='seed'>seed</li></a>
  </ul>
</div><!-- end footer  -->

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_index_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div id='blog'>
  <h3><%= @post.title %></h3>

  <%= @post.date %>

  <%= @post.content %>

<% if logged_in? %>
  <%= link_to 'Edit', edit_blog_path(@post) %> |
<% end %>
<%= link_to 'Back', blog_index_path %>
</div><!-- end -->

app/views/welcome/index.html.erb
<div id='wel-con' class='welcome'>
  <h1 class='words'>Welcome!</h1>
  <p>
    Hello, My name is <span id='name'>Chris Wenner</span>.
    It looks like you have found your way to my personal website!<br>
  </p>
</div><!-- end wel-con -->

<div id='side-feed' class='welcome'>
  <a class="twitter-timeline" href="https://twitter.com/crwenner" data-widget-id="268528039028199424" width='270px' height='368px'>Tweets by @crwenner</a>
  <script>
    !function(d,s,id){
      var js,fjs=d.getElementsByTagName(s)[0];

      if(!d.getElementById(id)){
        js=d.createElement(s);
        js.id=id;js.src="//platform.twitter.com/widgets.js";
        fjs.parentNode.insertBefore(js,fjs);
      }
    }(document,"script","twitter-wjs");
  </script>

  <div id='side2'>
  <span id='word2'>Recent Portfolio updates</span>
</div><!-- end side with portfolio -->

</div><!-- end side -->

<div id='blog-space'>
  <h1 class='words'>Recent Posts</h1>
</div><!-- end blog space -->

<% @posts.each do |post| %>
<div id='mini-blog'> 
  <div class="date-wrapper-container">
    <div class="wrapper-container">
      <%= post.date %>

    </div><!-- wrapper-container -->
  </div><!-- date-wrapper-container -->

  <h3><%= link_to post.title, blog_path(post) %></h3>

  <%= post.content %>

</div><!-- end mini-blog -->
<% end %>
    
<div id='footer'>
  <ul>
    <a href='http://www.facebook.com'><li class='facebook'>f</li></a>
    <a href='http://www.twitter.com'><li class='twitter'>t</li></a>
    <li class='me'>Created by Chris Wenner</li>
    <a href='http://www.seedcoworking.com'><li class='seed'>seed</li></a>
  </ul>
</div><!-- end footer  -->